CREATE TABLE City (
    CityID SERIAL PRIMARY KEY NOT NULL,
    CityName VARCHAR(58) NOT NULL,
    Latitude FLOAT NOT NULL,
    Longitude FLOAT NOT NULL,
    Elevation FLOAT NOT NULL,
    CityPopulation INT
);

CREATE TABLE Map (
    MapID SERIAL PRIMARY KEY NOT NULL,
    CityID INT REFERENCES City(CityID) NOT NULL
);

CREATE TABLE Game (
    GameID SERIAL PRIMARY KEY NOT NULL,
    MapID INT REFERENCES Map(MapID) NOT NULL,
    GameDate DATE NOT NULL,
    GameTime TIME NOT NULL,
    Points INT NOT NULL
);